name: clippy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  envied: ^0.3.0+3
  equatable: ^2.0.0
  google_sign_in:
  meta:
  firebase_auth:
  firebase_storage:
  email_validator:
  font_awesome_flutter:
  flutter_staggered_grid_view:
  circular_menu :
  flutter_quill: 8.6.0
  cloud_firestore: ^4.9.3
  easy_stepper: 0.8.3
  google_fonts: ^6.1.0
  cached_network_image:
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  get: ^4.6.6
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3


flutter:
  uses-material-design: true
  #library for assets
  assets:
    - assets/images/
    - assets/DB/papers/
    - assets/icons/
    - assets/images1/